---
apiVersion: v1
kind: Service
metadata:
  name: gitbook-service
spec:
  selector:
    app: gitbook
  type: NodePort
  ports:
  - name: gitbook
    protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitbook-deployment
  labels:
    app: gitbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitbook
  template:
    metadata:
      labels:
        app: gitbook
    spec:
      containers:
      - name: gitbook
        image: gitbook:offline
        command: [ "gitbook", "serve", "/root/books", "--no-watch", "--no-live" ]
        ports:
        - containerPort: 4000
          name: gitbook
        volumeMounts:
          - name: gitbook-data
            mountPath: /root/books
      volumes:
        - name: gitbook-data
          hostPath:
            path: /root/GitBook/hbook
